# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Summer in Sitka
email: jonathan.kt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sitka is a small Alaska community in the heart of the world’s largest
  temperate rainforest, perched on the North Pacific, set among mountains
  and glaciers. Over 150 students have come to Sitka the last four years.
  You can too.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://summerinsikta.com" # the base hostname & protocol for your site
assetsurl: "https://s3-us-west-2.amazonaws.com/sis-assets/"
imagesurl: "https://s3-us-west-2.amazonaws.com/sis-assets/images/"
#twitter_username: jekyllrb
github_username:  javbotero

# Build settings
markdown: kramdown
exclude: [vendor] # For travis: http://jekyllrb.com/docs/continuous-integration/
